import type { Metadata } from 'next'
import { Inter, Nunito } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'
import ClientOnly from '@/components/client-only';
import RegisterModal from '@/components/modals/register-modal';
import { ToasterProvider } from './providers/toaster-provider';
import LoginModal from '@/components/modals/login-modal';
import getCurretUser from './actions/getCurrentUser';

const font = Nunito({ 
  subsets: ['latin'], 
});


export const metadata: Metadata = {
  title: 'AirBnb',
  icons : [
    {
      url : '/logo.svg',
      href : '/logo.svg'
    }
  ],

  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurretUser();

  return (
    <html lang="ru">
      <body className={font.className}>
        <ClientOnly>
          <RegisterModal/>
          <LoginModal/>
          <ToasterProvider/>
          <Navbar currentUser={currentUser}/>
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
